### ISSUE TITLE
Запуск Telegram инстанса дважды

### ISSUE THREAD

**Issue by ozeranskii** [VegaAbsolute/IotVegaNotifier#3]
Кажется, что инстанс телеграм бота запускается дважды
```bash
0|npm      | October 2, 2019 5:36 PM: [Telegram] Error ETELEGRAM . ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
0|npm      | October 2, 2019 5:36 PM: [Telegram] Error ETELEGRAM . ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
0|npm      | October 2, 2019 5:36 PM: [Telegram] Unavailable telegram
0|npm      | October 2, 2019 5:36 PM: [Telegram] Unavailable telegram
```

**Comment by alk120ger** [comment]
Вероятнее всего это происходит в следствии того что приложение несколько раз успевает запросить состояния с телеграм ботом (что вполне нормально). Убедитесь что бот больше не используется другими приложениями и что IotVegaNotifier запущена в одном экземпляре на одной машине.

**Comment by ozeranskii** [comment]
Бот не используется другими приложения. Позже я проверю свою гипотезу происхождения этого поведения.
